export const categoryConstants = {
    GET_ALL_CATEGORIES_REQUEST : 'GET_ALL_CATEGORIES_REQUEST',
    GET_ALL_CATEGORIES_SUCCESS : 'GET_ALL_CATEGORIES_SUCCESS',
    GET_ALL_CATEGORIES_FAILURE : 'GET_ALL_CATEGORIES_FAILURE',
    ADD_NEW_CATEGORY_REQUEST : 'ADD_NEW_CATEGORY_REQUEST',
    ADD_NEW_CATEGORY_SUCCESS : 'ADD_NEW_CATEGORY_SUCCESS',
    ADD_NEW_CATEGORY_FAILURE : 'ADD_NEW_CATEGORY_FAILURE',
}

export const productsConstants = {
    GET_ALL_PRODUCT_SLUG: 'GET_ALL_PRODUCT_SLUG'
}
